// app/keys/page.tsx
'use client'
import Header from '@/components/header/header'
import styles from '@/app/keys/page.module.css'
import { motion, useMotionValueEvent, useScroll } from 'framer-motion'
import { useState } from 'react'
import Footer from '@/components/footer/footer'

export default function Keys() {
    const [isVisible, setIsVisible] = useState(true)

    // Framer motion to get rid of useEffect and instead just use their scroll hook
    const { scrollY } = useScroll()
    useMotionValueEvent(scrollY, 'change', () => {
        listenToScroll(0, setIsVisible)
    })

    const listenToScroll = (
        height: number,
        callback: React.Dispatch<React.SetStateAction<boolean>>,
    ) => {
        let heightToHideFrom = height
        const winScroll =
            document.body.scrollTop || document.documentElement.scrollTop

        if (winScroll > heightToHideFrom) {
            callback(false)
        } else {
            callback(true)
        }
    }

    return (
        <>
            <div className={'h-screen flex flex-col justify-between'}>
                <Header
                    props={{
                        title: '',
                        subtitle: 'SSH & PGP Keys',
                        imageUrl: '/Keys.jpg',
                    }}
                />
                <motion.svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className={`w-10 h-10 md:w-14 md:h-14 ${styles['bounce']} mx-auto`}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: isVisible ? 1 : 0 }}
                    transition={{
                        duration: 0.8,
                        delay: isVisible ? 1.5 : 0.2,
                        ease: [0, 0.71, 0.2, 1.01],
                    }}>
                    <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15.75 17.25L12 21m0 0l-3.75-3.75M12 21V3"
                    />
                </motion.svg>
            </div>

            <div className="dark:text-white lg:mx-auto lg:flex lg:justify-evenly lg:space-x-8 px-4 md:px-8">
                <div className="space-y-4 pb-10" id="pgp-key">
                    <h3 className="text-xl md:text-2xl">PGP Key</h3>
                    <p className="max-w-xl">
                        Below is my PGP key I used to use for code signing on
                        GitHub. Nowadays it&apos;s never used, but it&apos;s
                        here for historical purposes and to verify that I was
                        the one who signed those commits.
                    </p>
                    <div className="w-full break-words rounded-[0.25rem] dark:bg-slate-800 bg-floralwhite-300 py-2 px-4 md:w-fit">
                        <code>
                            -----BEGIN PGP PUBLIC KEY BLOCK-----
                            <br className="hidden md:block" />
                            mDMEYugSJRYJKwYBBAHaRw8BAQdAKcublhX5k/SKdVEK7D7UQenuyFxdFOcNlDTT
                            <br className="hidden md:block" />
                            FYOqRu+0OU5hdGUgUmVwcm9nbGUgKFl1YmlLZXkgR1BHIEtleSkgPG5hdGUucmVw
                            <br className="hidden md:block" />
                            cm9nbGVAZ21haWwuY29tPoiTBBMWCgA7FiEEMaXPkdww2zH5XKH1BvXgR5QOnRIF
                            <br className="hidden md:block" />
                            AmLoEiUCGwMFCwkIBwICIgIGFQoJCAsCBBYCAwECHgcCF4AACgkQBvXgR5QOnRIX
                            <br className="hidden md:block" />
                            cQD+JfjCXbHiow+OG+b93FE1PkdPnoNiaPxu7RqKB4kbZr4BAMqdv+NaKr6VZxoe
                            <br className="hidden md:block" />
                            /QdzkwevUYf50+PjcQqOAt2sz8IIuDgEYugSJRIKKwYBBAGXVQEFAQEHQPnsyKC6
                            <br className="hidden md:block" />
                            ri7QCkwiHpA/sBpyO6Xv6ysWL+J5wUaG/GwAAwEIB4h4BBgWCgAgFiEEMaXPkdww
                            <br className="hidden md:block" />
                            2zH5XKH1BvXgR5QOnRIFAmLoEiUCGwwACgkQBvXgR5QOnRK+rwEAzKcbv4GBrP9C
                            <br className="hidden md:block" />
                            iS0zAwt8VrcYXRKpniNk/o8Wl5ac4b4A/1iZfIuzelWbO2W1ehd0vqMQ1fmdGlq7
                            <br className="hidden md:block" />
                            8fW3L6xyXysA =Daxa
                            <br />
                            -----END PGP PUBLIC KEY BLOCK-----
                        </code>
                    </div>
                    <p>
                        As a{' '}
                        <a
                            href="https://reprogle.org/natereprogle_pgp.gpg"
                            className="underline">
                            raw file
                        </a>{' '}
                        :
                    </p>
                    <div className="w-fit break-all rounded-[0.25rem] dark:bg-slate-800 bg-floralwhite-300 py-2 px-4">
                        <code>
                            {' '}
                            curl https://reprogle.org/natereprogle_pgp.gpg | gpg
                            --import{' '}
                        </code>
                    </div>
                </div>
                <div className="space-y-4 pb-8" id="ssh-ed25519-key">
                    <h3 className="text-xl md:text-2xl">SSH Key</h3>
                    <p>
                        Below is my SSH key. I use this almost exclusively for
                        GitHub commit signing.
                    </p>
                    <div className="w-full break-all rounded-[0.25rem] dark:bg-slate-800 bg-floralwhite-300 py-2 px-4 md:w-fit">
                        <code>
                            ssh-ed25519 <br className="block md:hidden" />
                            AAAAC3NzaC1lZDI1NTE5AAAAIHXj4naNfNjrKvj1Gm0WBAICOrmh3YEQe1h5KHmkFMMf
                        </code>
                    </div>
                    <p>
                        It has a fingerprint of{' '}
                        <code className="break-all rounded-sm dark:bg-slate-800 bg-floralwhite-300 p-[2px]">
                            SHA256:+Anww30dTyHENrG1+bkuJcZlhvIGGl+7j1x2VmUfdsg
                        </code>
                        .
                    </p>
                    <div className="flex flex-col space-y-4 pb-8">
                        <p>
                            As a{' '}
                            <a
                                href="https://reprogle.org/natereprogle_ssh.pub"
                                className="underline">
                                raw file
                            </a>{' '}
                            :
                        </p>
                        <code className="w-full break-all rounded-[0.25rem] dark:bg-slate-800 bg-floralwhite-300 py-2 px-4 md:w-fit">
                            curl https://reprogle.org/natereprogle_ssh.pub
                            &gt;&gt; ~/.ssh/authorized_keys
                        </code>
                    </div>
                </div>
            </div>

            <hr className={'text-raisinblack-400 bg-raisinblack-400 h-[2px]'} />
            <Footer />
        </>
    )
}

// src/app/modules/main/pages/keys/keys.component.ts
import { Component } from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';
import { LinkInjectorService } from 'src/app/modules/main/services/link-injector.service';

import { metaTags } from 'src/app/modules/main/metaTags';

@Component({
  selector: 'app-keys',
  templateUrl: './keys.component.html',
  styleUrls: ['./keys.component.css'],
})
export class KeysComponent {
  expanded = false;

  expandArrow = `
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="h-6 w-6"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M8.25 4.5l7.5 7.5-7.5 7.5"
      />
    </svg>
  `;

  shrinkArrow = `
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
      class="h-6 w-6"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M4.5 15.75l7.5-7.5 7.5 7.5"
      />
    </svg>
  `;

  constructor(
    private metaService: Meta,
    private titleService: Title,
    private linkInjector: LinkInjectorService
  ) {
    titleService.setTitle('Keys - Nate Reprogle');
    metaService.addTags(metaTags);

    linkInjector.createLink('canonical', 'https://reprogle.org');
    linkInjector.createLink('preconnect', 'https://fonts.google.com');
    linkInjector.createLink('preconnect', 'https://fonts.gstatic.com', true);
  }

  setState(state: boolean) {
    this.expanded = state;
  }
}

<div class="relative overflow-hidden">
  <app-header
    headerText=""
    mainText="PGP & SSH Keys"
    footerText="For use with GitHub and secure messaging"
    image="/assets/Keys.jpg"
    imageAlt="Stock photo of lock with binary surrounding it"
  ></app-header>
  <div
    class="my-5 px-5 text-white md:mx-auto md:flex md:max-w-screen-md md:flex-col md:justify-evenly md:space-y-2 lg:max-w-screen-lg xl:max-w-screen-xl"
  >
    <div class="flex flex-col space-y-4 pb-10" id="pgp-key">
      <h3 class="text-xl md:text-2xl">PGP Key</h3>
      <p>Below is my PGP key I use for code signing on GitHub.</p>
      <div class="w-full break-words rounded-[0.25rem] bg-slate-800 py-2 px-4 md:w-fit">
        <code>
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          <br class="hidden md:block" />
          mDMEYugSJRYJKwYBBAHaRw8BAQdAKcublhX5k/SKdVEK7D7UQenuyFxdFOcNlDTT
          <br class="hidden md:block" />
          FYOqRu+0OU5hdGUgUmVwcm9nbGUgKFl1YmlLZXkgR1BHIEtleSkgPG5hdGUucmVw
          <br class="hidden md:block" />
          cm9nbGVAZ21haWwuY29tPoiTBBMWCgA7FiEEMaXPkdww2zH5XKH1BvXgR5QOnRIF
          <br class="hidden md:block" />
          AmLoEiUCGwMFCwkIBwICIgIGFQoJCAsCBBYCAwECHgcCF4AACgkQBvXgR5QOnRIX
          <br class="hidden md:block" />
          cQD+JfjCXbHiow+OG+b93FE1PkdPnoNiaPxu7RqKB4kbZr4BAMqdv+NaKr6VZxoe
          <br class="hidden md:block" />
          /QdzkwevUYf50+PjcQqOAt2sz8IIuDgEYugSJRIKKwYBBAGXVQEFAQEHQPnsyKC6
          <br class="hidden md:block" />
          ri7QCkwiHpA/sBpyO6Xv6ysWL+J5wUaG/GwAAwEIB4h4BBgWCgAgFiEEMaXPkdww
          <br class="hidden md:block" />
          2zH5XKH1BvXgR5QOnRIFAmLoEiUCGwwACgkQBvXgR5QOnRK+rwEAzKcbv4GBrP9C
          <br class="hidden md:block" />
          iS0zAwt8VrcYXRKpniNk/o8Wl5ac4b4A/1iZfIuzelWbO2W1ehd0vqMQ1fmdGlq7
          <br class="hidden md:block" />
          8fW3L6xyXysA =Daxa
          <br />
          -----END PGP PUBLIC KEY BLOCK-----
        </code>
      </div>
      <p>
        As a
        <a href="https://reprogle.org/natereprogle_pgp.gpg" class="underline"> raw file </a>
        :
      </p>
      <div class="w-fit break-all rounded-[0.25rem] bg-slate-800 py-2 px-4">
        <code> curl https://reprogle.org/natereprogle_pgp.gpg | gpg --import </code>
      </div>
    </div>
    <div class="flex flex-col space-y-4 border-t pb-8" id="ssh-ed25519-key">
      <h3 class="mt-2 text-xl md:text-2xl">SSH Key</h3>
      <p>Below is my SSH key. I don&apos;t normally use it, but it&apos;s here if needed.</p>
      <div class="w-full break-all rounded-[0.25rem] bg-slate-800 py-2 px-4 md:w-fit">
        <code>
          ssh-ed25519
          <br class="block md:hidden" />
          AAAAC3NzaC1lZDI1NTE5AAAAIHXj4naNfNjrKvj1Gm0WBAICOrmh3YEQe1h5KHmkFMMf
        </code>
      </div>
      <p>
        It has a fingerprint of
        <code class="break-all rounded-sm bg-slate-800 p-[2px]">
          SHA256:+Anww30dTyHENrG1+bkuJcZlhvIGGl+7j1x2VmUfdsg
        </code>
        .
      </p>
      <div class="flex flex-col space-y-1">
        <p>
          As a
          <a href="https://reprogle.org/natereprogle_ssh.pub" class="underline"> raw file </a>
          :
        </p>
        <code class="w-fit break-all rounded-[0.25rem] bg-slate-800 py-2 px-4">
          curl https://reprogle.org/natereprogle_ssh.pub &gt;&gt; ~/.ssh/authorized_keys
        </code>
      </div>
    </div>
    <div class="flex flex-col space-y-2" id="ssh-rsa-key">
      <h3 class="text-md mt-2 md:text-lg">RSA Key</h3>
      <p>
        I also have an old RSA Key I used to use for private servers and services, It may be good to have it here just
        in case!
      </p>
      <br />
      <button class="flex w-fit cursor-pointer py-2 pr-4 lg:py-0" (click)="setState(!expanded)">
        @if(expanded) {
        <ng-container>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="h-6 w-6"
          >
            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
          </svg>
          <span class="pl-1">Click to collapse</span>
        </ng-container>
        } @else {
        <ng-container>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="h-6 w-6"
          >
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
          </svg>
          <span class="pl-1">Click to expand</span>
        </ng-container>

        }
      </button>

      @if(expanded) {
      <div id="collapsable-key">
        <div class="flex flex-col space-y-2">
          <div class="w-full break-all rounded-[0.25rem] bg-slate-800 py-2 px-4 lg:w-[80%]">
            <code class="break-all">
              ssh-rsa
              AAAAB3NzaC1yc2EAAAADAQABAAACAQDwA/XYgPDUwKvS4nxb/qMd35uzIXqMuJSn0M57Y2cGrlaY90zlu/xBXKc2p+Tcs9VQnP4Zh+nrr01FZB707H0iwK3VS5VUGO6d42hw3QOWpCzRU9anOr4zUNlvesEYhv04wW5OJW/IAtnGZAWQ1QXYHYYAGb4Lac/OcLIxRj2HU9mnhyO4puhL/iSyyRD8rP8Kjnc9U+a0eFnbBp8vqVXEYaKwjHFVr5OGGyyE1o3bTTtfP8C9mCvlbgZFaFQEbPhFdKGF5lRcjSlKF5E1lqp+JehqaKLTCamzfQuFTxCHydmtdKF0ceTuLqCeBNeKMNf+rEQ76jKXIVTxLWOFfiBLauBJMMxuemWpaPCbM5m+W0tN7bkx617KzuaB3DPYASepj8jL7zpLX/9R+ODbgBgdcde46X91zHJsmy9HCFkMNKCQv41FOl51O8+uFW2pR8Xv9gn2SOsPAQgIDXg4ACuJefTYzHo4ZF5isKGsGgwC+rpM7GVIkzS/r8c/foH2KRf9s0+T9aiqjVpAd3Q7hecbPfn+sWzPcpmyZ3WJiS/TPVd4ErSQSH3DO7fA2Hs+pwcvHIYrcmuhCqsRasJxI5tCZ3+vgPTo+ENoyh9wIDNek4i9aBRsVwZg4WBjIP+uX7UCEiiWOAUps/x8XmNDKQVhy1FGs9sxaH7TqYOhqwRHEQ==
            </code>
          </div>
          <p class="pb-4">
            It has a fingerprint of
            <code class="break-all rounded-sm bg-slate-800 p-[2px]">
              MD5:96:46:4b:a8:eb:0b:90:f3:f5:a7:8c:b2:3c:d3:d3:ba
            </code>
            .
          </p>
          <div class="flex flex-col space-y-1">
            <p>
              As a
              <a href="https://reprogle.org/natereprogle_rsa.pub" class="underline"> raw file </a>
              :
            </p>
            <code class="w-fit break-all rounded-[0.25rem] bg-slate-800 py-2 px-4">
              curl https://reprogle.org/natereprogle_rsa.pub &gt;&gt; ~/.ssh/authorized_keys
            </code>
          </div>
        </div>
      </div>
      }
    </div>
  </div>
</div>
